#!/bin/bash

DOMAIN="jeromepatrick.tech"
WEB_SERVER_IP="54.236.30.233"

# Create the file if it doesn't exist
echo "@ IN A $WEB_SERVER_IP" > /etc/bind/db.$DOMAIN

# Restart BIND service (DNS server)
systemctl restart bind9

# Verify DNS configuration using dig
echo "Verifying DNS configuration for $DOMAIN"
dig $DOMAIN
